swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:4200
basePath: /api/v1
schemes:
  - http
# API permettant de lister les utilisateurs
paths:
  /user/lists:
    get:
      tags:
        - User Module
      summary: ListUsers
      description: API for Users List
      produces:
        - application/json
      responses:
        '200':
          description: Listing Successfully
          schema:
            $ref: '#/definitions/ListUsersResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
################################ API permettant d'enregistrer une ARGENTBANK................
  /argentBank/register:
    post:
      tags:
        - Argent Bank Module
      summary: Register
      description: API for Register Argent Bank
      parameters:
        - in: body
          name: body
          description: Register Payload
          required: true
          schema:
            $ref: '#/definitions/register'
      produces:
        - application/json
      responses:
        '200':
          description: Register Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  register:
    properties:
      title:
        type: string
        description: Argent Bank Title
      accountNumber:
        type: number
        description: Argent Bank Account Number
      accountPrice:
        type: number
        description: Argent Bank Account Price
      subTitle:
        type: string
        description: Argent Bank sub title
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
